### ISSUE TITLE
PostgreSQL Example

### ISSUE THREAD

**Issue by halojemrufus** [RedTurtle/eve-sqlalchemy#10]
Are there any PostgreSQL examples available?

**Comment by toxsick** [comment]
have a look [here](http://eve-sqlalchemy.readthedocs.org) or [here](https://github.com/RedTurtle/eve-sqlalchemy/tree/master/examples) ;)

**Comment by toxsick** [comment]
Just to make this clear. If you define a `SQLALCHEMY_DATABASE_URI` like this you should be fine:

```python
SQLALCHEMY_DATABASE_URI = 'postgresql://scott:tiger@localhost/mydatabase'
```

For more info on this refer to the SQLAlchemy [documentation](http://docs.sqlalchemy.org/en/rel_0_9/core/engines.html#postgresql)
