### ISSUE TITLE
How to use OR filter 

### ISSUE THREAD

**Issue by lebanonsky** [RedTurtle/eve-sqlalchemy#117]
From Sqlaclhemy:

`filter(or_(User.name == 'ed', User.name == 'wendy'))
`
How can this be applied this to eve-filter?

**Comment by solinas3000** [comment]
I'm not able to find a working example to perform or_ operation with two like operation in my request API. Could you please provide one working example for that ? Something like ?where={'Brand':'%var1%' or 'Model':'%var2%'}

**Comment by solinas3000** [comment]
i'm putting this here , in case someone is looking for an example.
element?where={"or_":[{"ID":523},{"ID":532}]}
