### ISSUE TITLE
license='GPL' in setup.py

### ISSUE THREAD

**Issue by winny-** [RedTurtle/eve-sqlalchemy#121]
The `LICENSE` file looks like a modified BSD 3-clause license and an classifier in `setup.py` agrees with this; however, the `license='GPL'` keyboard argument in `setup.py` conflicts with this (and it affects the License field on PyPI).

**Comment by dkellner** [comment]
Thank you for reporting this. I will have a look into the whole packaging process before releasing 0.5. Expect some overall cleanup :).

**Comment by dkellner** [comment]
This was fixed with #137.
