### ISSUE TITLE
multi-column primary key

### ISSUE THREAD

**Issue by nypgand1** [RedTurtle/eve-sqlalchemy#13]
In the [docs of SQLAlchemy](http://docs.sqlalchemy.org/en/rel_0_9/core/metadata.html), it says:
> Multiple columns may be assigned the primary_key=True flag which denotes a multi-column primary key, known as a composite primary key.

But in eve-sqlalchemy and cerberus, we validate the `unique` constraint in the scope of **single column**.

Any suggestions on this issue?

**Comment by nypgand1** [comment]
@nicolaiarocci Hi, any suggestions on this issue?

**Comment by goneri** [comment]
I think we can also just catch the DB constraint failure and for free we will get better performance. So far Eve-SQLAlchemy just generate suspicious 500 err.

**Comment by mandarvaze** [comment]
@nypgand1 The issue is marked as closed. Did it solve your problem ?
I'm using Eve-SQLAlchemy 0.4.1, and still seeing this issue (i.e. unique constrain checked on single column rather than on a composite key)

@nicolaiarocci help ?

**Comment by nypgand1** [comment]
@mandarvaze Sorry. I'm not quite sure whether it is solved or not , because I don't use it now.

**Comment by nicolaiarocci** [comment]
Hi guys, I don't work on the sql-alchemy extension and don't use it in production so I'm afraid I can offer no help here.

**Comment by nicolaiarocci** [comment]
PS in Eve, `unique` rule is a feature of the Mongo validator.

**Comment by bthorben** [comment]
Workaround: You can basically just remove the unique constraint. Eve will not check and if you actually enter something into the db that violates your constraint you will get an IntegrityError

**Comment by bthorben** [comment]
BTW: Could we please reopen this issue? It still exists and this is the place with the most information about it.
