### ISSUE TITLE
Question about development and testing

### ISSUE THREAD

**Issue by bomb-on** [RedTurtle/eve-sqlalchemy#132]
I wanted to submit a PR with a tiny fix but I am confused about the current state of our branches. I branched-off from `develop`, did my "tiny fix" and tried to run tests. However, it seems that my tests are always failing when running [`TestAssociationProxy`](https://github.com/RedTurtle/eve-sqlalchemy/blob/develop/eve_sqlalchemy/tests/test_association_proxy.py). I have noticed that these tests exist in `develop` branch, but not in the master.

So, how to proceed from here? If i submit PR, tests will fail. I'm not sure how to fix it or should I even try to fix it in the first place because that file was probably removed with a reason :)
Since we are still not running any CI tool in the background, should I even care about those tests failing?

**Comment by dkellner** [comment]
Can you try to branch from `master`? The tests should work there. I'm actually not yet sure about if we should maintain both a master and develop branch (and maybe version branches, too). It feels like a lot of overhead. What do you think about that?

**Comment by bomb-on** [comment]
I usually try to follow [this workflow](http://nvie.com/posts/a-successful-git-branching-model/) in my projects. Essentially - there are `master` in which only releases are merged and `develop` where all the development is and both are "infinite" branches (since we always develop and release :)). Then for each specific dev process, I branch-off from develop and eventually merge back the feature branch into it.

I'll try to branch-off from master a bit later and see if tests are passing...

**Comment by bomb-on** [comment]
Sorry for delay, I was busy with some other stuff... Anyways, branching off from `master` did the trick, so I submitted my PR (#133) now.

While we're on the topic of testing... I have noticed that we are actually testing against SQLite database, not PostgreSQL? Is that true? If so, do we have any plans to switch to PostgreSQL any time soon?

**Comment by dkellner** [comment]
Don't worry about the delay, I've been pretty busy the last week, too ;). You're right, we're testing against an in-memory SQLite database (specified by ```SQLALCHEMY_DATABASE_URI = 'sqlite:///'``` in `test_settings.py`). At the moment there are no plans to change this - and I'm not sure if we really should. You could ask for MySQL or other SQLAlchemy-supported databases, too.

Nevertheless, I agree that testing on different databases would be great. So maybe we can leave SQLite the default (as it requires no additional setup and is totally fine for covering most "high-level" application code), but provide an easy way for users to run the tests against PostgreSQL/MySQL?

**Comment by bomb-on** [comment]
Ah yes, you are absolutely right about MySQL and others... Well, definitely something to think about :)

I will close this for now although there is still a question about the development process open, maybe this is something that belongs solely in documentation so that everyone can be aware of it?

**Comment by joystein** [comment]
Another write-up about git branching:

https://about.gitlab.com/2014/09/29/gitlab-flow/

I also tend to agree that git-flow is usually too much ceremony for little gain.
