### ISSUE TITLE
Missing CommonColumns import in documentation example.

### ISSUE THREAD

**Issue by edthedev** [RedTurtle/eve-sqlalchemy#14]
I guess this is mostly a documentation question.

On this page: 
http://eve-sqlalchemy.readthedocs.org/

Is CommonColumns just a design pattern, or something provided as part of SQLAlchemy? 
If it something that can be imported, the import could be added.

If it is something custom, it would help to declare CommonColumns inline in the example, and simply mention that it is not strictly necessary - rather than having it in a separate code block later.

**Comment by amleczko** [comment]
The tutorial explicitly explains why the CommonColumns abstract class is used in http://eve-sqlalchemy.readthedocs.org/en/stable/tutorial.html
