### ISSUE TITLE
DOMAIN not connected to EVE in example.

### ISSUE THREAD

**Issue by edthedev** [RedTurtle/eve-sqlalchemy#15]
At this page, http://eve-sqlalchemy.readthedocs.org/

the example code provided does not connect DOMAIN into the settings dictionary, resulting in an error message.

    raise ConfigException('DOMAIN dictionary missing or wrong.')
    eve.exceptions.ConfigException: DOMAIN dictionary missing or wrong.

A solution to this is to declare a simple SETTINGS dictionary, with the DOMAIN settings in it, and pass it into the Eve constructor:
     
    SETTINGS = {
          'DOMAIN': DOMAIN,
      }
    app = Eve(settings=SETTINGS, validator=ValidatorSQL, data=SQL)

**Comment by edthedev** [comment]
Looking through the docs source code, it looks like this is due to Eve auto-detecting a settings.py file and using it for the default option.

Unfortunately, the existence of the settings.py file is not explicitly mentioned on the page.

I can see a few ways to remedy this:

1. Explicitly document the file name magic being used to connect Eve with the settings. While this would be nice, it seems more about Eve and less about eve_sqlalchemy.
2. Update the examples to directly explicitly import the settings, and pass it into the Eve constructor. This seems simpler, as it doesn't require unnecessary wording.

**Comment by edthedev** [comment]
Here's a possible change to sqla_example.py that would remove the magic, without spending time with words explaining the magic happening when Eve looks for settings.py:

    from settings import DOMAIN, SQLALCHEMY_DATABASE_URI, DEBUG

    SETTINGS = {
        'DOMAIN': DOMAIN,
        'SQLALCHEMY_DATABASE_URI': SQLALCHEMY_DATABASE_URI,
        'DEBUG': DEBUG,
    }

    app = Eve(settings=SETTINGS, validator=ValidatorSQL, data=SQL)

There is almost certainly a more elegant way to do this, that still conveys what is happening, but it alludes me at the moment.

**Comment by edthedev** [comment]
I should mention that my main reason for investigating eve_sqlalchemy is to move away from the implicit filename magic that Django uses around it's settings.py file and it's models.py file.

I suspect that others with my use case will also land on this page, looking at this toolchain, so a simple clarification here could be very valuable to the community. :)

**Comment by amleczko** [comment]
You are right - I will update the docs.

**Comment by amleczko** [comment]
The http://eve-sqlalchemy.readthedocs.org/en/stable/trivial.html fixed that problem, too

**Comment by mandarvaze** [comment]
@edthedev 
I have a settings.py file (magic filename) and it contains DOMAIN dict definition, it is in same folder as run.py

This is exactly same filenames and folder structure as "default" Eve app, which uses Mongo driver rather than SQLAlchemy. Without eve-sqlalchemy, it works fine. i.e. DOMAIN is picked up from settings.py file, then why does it NOT work for eve-sqlalchemy ?

**Comment by mandarvaze** [comment]
Turns out the problem was with my DOMAIN definition. Unfortunately the error message for `missing` and `wrong` definition is same.
Also, it would be helpful if "what is wrong" is explained in the error message.

**Comment by m3talstorm** [comment]
What was the problem with your DOMAIN definition mandarvaze, I seem to be having the same problem when I move my settings.py into a different directory.
