### ISSUE TITLE
Documentation needs trivial example

### ISSUE THREAD

**Issue by edthedev** [RedTurtle/eve-sqlalchemy#17]
An additional example is needed in the documentation of the simplest possible API:

This example should include:
 - A trivial 'no authentication' auth setup
 - Just one or two database tables

**Comment by edthedev** [comment]
Here's something.

https://github.com/edthedev/eve-sqlalchemy/blob/master/examples/trivial.py

**Comment by amleczko** [comment]
Fixed in #19
