### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by aguirrel** [RedTurtle/eve-sqlalchemy#3]
Hi guys!

Great Work!!!  I'm very interested in this project but I'm in doubt about if this sqlalchemy-eve is full feature compared with eve/mongodb.  Has this project any known drawback at the moment? Something that can't do?

Thanks a lot!

**Comment by amleczko** [comment]
We are aiming to get the same features that are provided by the mongodb data layer. There are some differences like supporting media, etc. but on the API level everything should behave the same way. If it's not - it is a bug :)
I think @nicolaiarocci is planning to move the mongo part outside the eve core with the 0.6 release. This would help keeping extensions up-to-date.
