### ISSUE TITLE
Response Eve-SQLAlchemy not as expected

### ISSUE THREAD

**Issue by evertg** [RedTurtle/eve-sqlalchemy#33]
Hi,
Thank you for your good work.
I just installed and the application seems to work for the most. http://localhost:5000/ and http://localhost:5000/ give responses.
However:
1: I get an error on http://localhost:5000/account/1.
2: http://localhost:5000/account?id=1 gives me the response underneath. The underscores do not seem to comply to your documentation, nor standard json (according to jsonapi.org).

So, what do I do wrong not to get both  http://localhost:5000/account/1  and the response right?

Thanks in advance and have a nice day,

Evert

{
    "_links": {
        "self": {
            "href": "account",
            "title": "account"
        },
        "parent": {
            "href": "/",
            "title": "home"
        }
    },
    "_items": [
        {
            "accountname": "eve",
            "salt": "eve",
            "_etag": null,
            "_updated": "Tue, 21 Apr 2015 09:36:25 GMT",
            "password": "550e8400-e29b-41d4-a716-446655440000",
            "id": 1,
            "_created": null
        }
    ],
    "_meta": {
        "page": 1,
        "total": 1,
        "max_results": 25
    }
}

**Comment by amleczko** [comment]
The response format is provided by github.com/nicolaiarocci/eve/ - our plugin only adds sqlalchemy support. Please try to ask question there.
