### ISSUE TITLE
question about the new operator parser (possible regression)

### ISSUE THREAD

**Issue by kiniou** [RedTurtle/eve-sqlalchemy#34]
Hi @amleczko ,

Since your commit 8b7d4aab, our tests are broken (cf. https://travis-ci.org/kiniou/talaos-inventory/jobs/60720548#L242) and it appears the culprit is the method attr.op() you use to call the requested operator.

In substance, when I pass some query argument like:

    /asset?where={'name':'startswith(\"computer\")}`

Now (0.3.1 release) sqlalchemy translate this query to:

    asset.name startswith "computer"

instead of (pre 0.3.1 release)

    asset.name like "computer%"

I may have missed something but it seems the attr.op() is not behaving like you want it to. And I don't know why since i'm not really used to the inner working of SQLAlchemy.

I managed to find the tests about the parse_dictionnary() method but none of those parsed operators are tested in `tests/get.py` (or maybe i'm too tired to find those tests ... ).

Cheers

**Comment by kiniou** [comment]
After re-reading the corresponding documentation about sqlalchemy.orm.properties.ColumnProperty.op(), I've updated the pull request with a fix that try to make a fallback on attr.op() if the operator doesn't exists in the ColumnProperty instance.

The only testcase still in failure is the `ilike` operator which exists in ColumnProperty and is tested against the returned value of attr.op() which IMHO should not be tested.

**Comment by amleczko** [comment]
You are right - it was a unintentional regression. Thanks for the PR. I have merged it and fixed some old tests to work with the new format.

**Comment by kiniou** [comment]
Thank you for merging those changes.

I'm not sure but I think you may have missed my last 2 commits in the PR.

- kiniou/eve-sqlalchemy@849ddc2e31edfbd1661bbd8c1761bda044631ed1 : 
This commit is just related to some pep8 mistake i forgot to fix.

- kiniou/eve-sqlalchemy@7463432df2f4ee540454704abb55adffd29db84b :
This one was just a proposal to remove those particular operators from the tests.
To be honest, I'm not sure the returned filter of `parse_dictionnary` should be tested by `eve_sqlalchemy` since it's already tested in `sqlalchemy`. But maybe you are not confident with `sqlalchemy`'s tests :)

**Comment by amleczko** [comment]
They were added don't worry.
The `parse_dictionary` is a layer on top of `sqlalchemy` and I want to be sure that the fallback is working properly.
And yes - I trust `sqlalchemy`'s tests :-)

**Comment by kiniou** [comment]
Ok, fair enough ;)
