### ISSUE TITLE
eve-sqlalchemy vs sqlalchemy branch in eve

### ISSUE THREAD

**Issue by arieb** [RedTurtle/eve-sqlalchemy#4]
How does this project relate to the sqlalchemy branch inside eve? and more importantly which one should be used?

**Comment by nicolaiarocci** [comment]
This is just off the press:
http://nicolaiarocci.com/announcing-eve-sqlalchemy-the-official-sql-extension-for-the-eve-rest-framework/

:smile:

**Comment by nicolaiarocci** [comment]
PS: sqlalchemy branch on eve repositori is going to be removed.

**Comment by toxsick** [comment]
What still confuses me are imports like [this](https://github.com/RedTurtle/eve-sqlalchemy/blob/master/examples/settings.py#L9):

```python
from eve.io.sql.decorators import registerSchema
```
Souldn't it be imported from the extention with `from eve_sqlalchemy.decorators import registerSchema`

regards Hannes

**Comment by nicolaiarocci** [comment]
Yeah. Please submit a PR to fix the docs (or wait until Andrew fixes it :smile:)

**Comment by toxsick** [comment]
here you are #5 :)

**Comment by nicolaiarocci** [comment]
:+1:

**Comment by amleczko** [comment]
Thanks for pointing that out.
