### ISSUE TITLE
Query a relationship

### ISSUE THREAD

**Issue by samtux** [RedTurtle/eve-sqlalchemy#55]
Is possible to filter by fields in a collection?. I require to filter the following response:

https://gist.github.com/samtux/bcf4783f450aa3ca905f

I tried the following queries according to the documentation python-evis:

```
respuesta?where={"pregunta.pregunta.formulario.idgrupotrabajo":540544}
respuesta?where={"pregunta":{"formulario":{"idgrupotrabajo":540544}}}
```
But I have not been able to perform the filter.

Thanks.

**Comment by amleczko** [comment]
I don't think that this is currently possible. Sorry.
