### ISSUE TITLE
UnicodeEncodeError when filtering unicode string

### ISSUE THREAD

**Issue by terrysclaw** [RedTurtle/eve-sqlalchemy#58]
http://127.0.0.1:5000/api/v1/user_profiles?where={"name":"like(\"%25林%\")"}

File "C:\Users\SiuCheongTerry\OneDrive\Projects\to-do\tochange.com.hk\server\venv\lib\site-packages\eve_sqlalchemy\parser.py", line 43, in parse_dictionary
        conditions += parse('{0}{1}'.format(k, v), model)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u6797' in position 7: ordinal not in range(128)

parser.py
line 42-47
        try:
            conditions += parse('{0}{1}'.format(k, v), model)
        except ParseError:
            pass
        else:
            continue

to...

        try:
            if(type(v) is unicode):
                conditions += parse('{0}{1}'.format(k, v.encode('utf-8')), model)
            else:
                conditions += parse('{0}{1}'.format(k, v), model)
        except ParseError:
            pass
        else:
            continue

**Comment by amleczko** [comment]
can you convert this issues to PR with a small test?

**Comment by terrysclaw** [comment]
Hi amleczko,
How to convert?

**Comment by amleczko** [comment]
It would be great!
Please read https://help.github.com/articles/creating-a-pull-request/ and https://help.github.com/articles/using-pull-requests/

**Comment by amleczko** [comment]
Thanks!
