### ISSUE TITLE
ValidatorSQL class doesn't handle/pass allow_unknown

### ISSUE THREAD

**Issue by lingfish** [RedTurtle/eve-sqlalchemy#70]
Hi, just discovered that the abovementioned class doesn't notice when `allow_unknown` is set to `True`.

The key lines missing/needed from Eve [are here](https://github.com/nicolaiarocci/eve/blob/develop/eve/io/mongo/validation.py#L59) (in `__init__`):

```python
        if resource:
            self.allow_unknown = config.DOMAIN[resource]['allow_unknown']
```

I've worked around this (and it works fine) by subclassing and adding those two lines.

**Comment by amleczko** [comment]
Can you make a PR instead with a tiny test?
